# Generated by Django 3.2.3 on 2021-06-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='notas',
            field=models.TextField(null=True),
        ),
    ]
